channels:
- 16
- 32
- 64
- 128
- 256
data_dir: /Users/sandunipinnawala/Documents/Git_Repos/monai-3d-spleen-seg-testing/data/Task09_Spleen
in_channels: 1
lr: 0.0001
num_res_units: 2
out_channels: 2
roi_size:
- 160
- 160
- 160
spatial_dims: 3
strides:
- 2
- 2
- 2
- 2
sw_batch_size: 4
